package com.unisinos.petrisimulator;

import java.awt.event.WindowEvent;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;
import org.apache.commons.io.FileUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author tuto_
 */
public class MainWindow extends javax.swing.JFrame {

    private PetriNet petri;

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();
        botAvancar = new javax.swing.JButton();
        botCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        inputJson = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        outputTable = new javax.swing.JTable();
        botFile = new javax.swing.JButton();
        botSave = new javax.swing.JButton();
        botReset = new javax.swing.JButton();

        fileChooser.setPreferredSize(new java.awt.Dimension(814, 597));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PetriSim");
        setLocation(new java.awt.Point(500, 50));

        botAvancar.setText("Avançar");
        botAvancar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botAvancarActionPerformed(evt);
            }
        });

        botCancelar.setText("Fechar");
        botCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botCancelarActionPerformed(evt);
            }
        });

        inputJson.setColumns(20);
        inputJson.setRows(5);
        jScrollPane1.setViewportView(inputJson);

        outputTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        outputTable.setColumnSelectionAllowed(true);
        outputTable.setEnabled(false);
        outputTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(outputTable);
        outputTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        botFile.setText("Ler arquivo");
        botFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botFileActionPerformed(evt);
            }
        });

        botSave.setText("Salvar rede");
        botSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botSaveActionPerformed(evt);
            }
        });

        botReset.setText("Resetar");
        botReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(botFile)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botReset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botAvancar))
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botAvancar)
                    .addComponent(botCancelar)
                    .addComponent(botFile)
                    .addComponent(botSave)
                    .addComponent(botReset))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botAvancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botAvancarActionPerformed
        // Se ainda não criou a rede
        if (petri == null) {
            // Desabilita entrada de dados
            inputJson.setEnabled(false);
            botFile.setEnabled(false);
            // Cria nova rede vazia
            petri = new PetriNet(new ArrayList<>(), new ArrayList<>(), new ArrayList<>());
            try {
                // Preenche rede com dados da entrada
                petri.createPetriNet(inputJson.getText());
            } catch (Exception e) {
                System.out.println("Erro ao criar a rede de Petri. Verifique se a entrada está correta!");
            }
            // Adiciona colunas para os lugares e transições
            DefaultTableModel tableModel = new DefaultTableModel();
            tableModel.addColumn("Ciclo");
            tableModel.addColumn("Relógio");
            petri.getLugares().forEach((l) -> {
                tableModel.addColumn(l.getLabel() + " (" + l.getTempo() + "Z)");
            });
            petri.getTransicoes().forEach((t) -> {
                tableModel.addColumn(t.getLabel());
            });
            outputTable.setModel(tableModel);
            // Se já criou a rede
        } else {
            // Realiza novo ciclo
            petri.step();
        }
        // Adiciona nova linha na tabela
        DefaultTableModel tableModel = (DefaultTableModel) outputTable.getModel();
        ArrayList<Integer> row = new ArrayList<>();
        row.add(petri.getCiclo());
        row.add(petri.getRelogio());
        petri.getLugares().forEach((l) -> {
            row.add(l.getMarcas());
        });
        for (int i = 0; i < tableModel.getColumnCount(); i++) {
            for (Transicao t : petri.getTransicoes()) {
                if (t.getLabel().equals(tableModel.getColumnName(i))) {
                    if (t.isHabil()) {
                        row.add(1);
                    } else {
                        row.add(0);
                    }
                    break;
                }
            }
        }

        tableModel.addRow(row.toArray());
        // Se finalizou a execução
        if (petri.isFinished()) {
            // Desabilita botão de avançar
            botAvancar.setEnabled(false);
        }
    }//GEN-LAST:event_botAvancarActionPerformed

    private void botCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botCancelarActionPerformed
        // Fecha janela
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_botCancelarActionPerformed

    private void botFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botFileActionPerformed
        int val = fileChooser.showOpenDialog(this);
        if (val == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            try {
                inputJson.setText(FileUtils.readFileToString(file));
            } catch (IOException ex) {
                Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_botFileActionPerformed

    private void botSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botSaveActionPerformed
        int val = fileChooser.showSaveDialog(this);
        if (val == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            try {
                FileUtils.writeStringToFile(file, inputJson.getText());
            } catch (IOException ex) {
                Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_botSaveActionPerformed

    private void botResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botResetActionPerformed
        petri = null;
        inputJson.setEnabled(true);
        botAvancar.setEnabled(true);
        botFile.setEnabled(true);
        outputTable.setModel(new DefaultTableModel());
    }//GEN-LAST:event_botResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botAvancar;
    private javax.swing.JButton botCancelar;
    private javax.swing.JButton botFile;
    private javax.swing.JButton botReset;
    private javax.swing.JButton botSave;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JTextArea inputJson;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable outputTable;
    // End of variables declaration//GEN-END:variables
}
